apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nextjs-sample-app
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: nextjs-sample-app
spec:
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER
      value: nginx
    - name: BP_WEB_SERVER_ROOT
      value: .next
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"
  source:
    git:
      url: https://github.com/seagomezar/nextjs-sample-app
      ref:
        branch: main
