apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nextjs-sample-app
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: nextjs-sample-app
spec:
  params:
    - name: dockerfile
      value: ./Dockerfile
    - name: docker_build_context
      value: nextjs-sample-app/
  source:
    git:
      url: https://github.com/seagomezar/nextjs-sample-app
      ref:
        branch: main
